

#pragma once

#define TILE(x,y) (x+(y*32))

enum INPUTEVENTS {
	TOUCH_DOWN,
	TOUCH_UP,
	TOUCH_HELD,
	KEY_B_DOWN,
	KEY_A_DOWN,
	KEY_X_DOWN,
	KEY_Y_DOWN,
	KEY_UP_DOWN,
	KEY_DOWN_DOWN,
	KEY_LEFT_DOWN,
	KEY_RIGHT_DOWN,
	KEY_START_DOWN,
	TIMEOUT
};

enum WINDOWOBJECTS {
	OBJ_UNDEF,
	LABEL,
	BUTTON,
	SELECTOR,
	CHECKBOX,
	RADIO,
	TEXT,
	SCROLL,
	SCROLLBAR
};

enum RDO_RESULT {
	RDO_UNSELECTED,
	RDO_SELECTED
};

enum CHK_RESULT {
	CHK_UNCHECKED,
	CHK_CHECKED
};

enum SEL_RESULT {
	SEL_UNSELECTED,
	SEL_SELECTED,
	SEL_ACTIVATED,
	SEL_ACTIVATED_X,
	SEL_ACTIVATED_Y
};

enum BTN_RESULT {
	BTN_UP,
	BTN_DOWN,
	BTN_ACTIVATED
};

enum WND_RESULT {
	WND_CANCEL,
	WND_IDLE,
	WND_OK,
	WND_SEL
};


enum SCROLL_RESULT {
	SCROLL_UNSELECTED,
	SCROLL_SELECTED,
	SCROLL_ACTIVATED,
	SCROLL_UP_REACHED,
	SCROLL_DOWN_REACHED
};


enum LOOKDATA {
		SEL_SIMPLE,
		SEL_CIRCLE,
		SEL_COMPLEX
};

typedef struct ICONBUTTONDATA {
	u8 x1; u8 y1;
	u8 x2; u8 y2;
	char title[32];
	u32 icon;
	int look;
	int ref;
}IconButtonData;

typedef struct WINDOWDATA {
	u8 x1; u8 y1;
	u8 x2; u8 y2;
	char* title;
	int type;
}WindowData;

typedef struct GUIDATA {
	u8 x1; u8 y1;
	u8 x2; u8 y2;
	char title[32];
	u32 buffer;  // or tile number 
	int color;
	int look;
	int ref;
}GUIData;


/*typedef union GUIDATA {
LabelData labelData;
ButtonData buttonData;
SelectorData selectorData;
}GUIData;*/

enum GUITILES {
	BLANK			=512,//START// tiles offset because I had to put it next to the text to save space
	UNDEF,           // gui or color is undefined 
	SELECTED,

	TITLE_TOP_LEFT,
	TITLE_TOP,
	TITLE_TOP_RIGHT,
	TITLE_LEFT,
	TITLE_BLANK,
	TITLE_RIGHT,
	TITLE_BOTTOM_LEFT,
	TITLE_BOTTOM,
	TITLE_BOTTOM_RIGHT,

	WINDOW_LEFT,
	WINDOW_BLANK,
	WINDOW_RIGHT,
	WINDOW_BOTTOM_LEFT,
	WINDOW_BOTTOM,
	WINDOW_BOTTOM_RIGHT,
	GROUP_TOP_LEFT,
	GROUP_TOP,
	GROUP_TOP_RIGHT,
	GROUP_BOTTOM_LEFT,
	GROUP_BOTTOM,
	GROUP_BOTTOM_RIGHT,
	GROUP_LEFT,
	GROUP_BLANK,
	GROUP_RIGHT,
	BUTTON_OK,
	BUTTON_CANCEL,
	UNDEF4,
	SUB_TITLE_TOP_LEFT,
	SUB_TITLE_TOP,
	SUB_TITLE_TOP_RIGHT,
	SUB_TITLE_LEFT,
	SUB_TITLE_BLANK,
	SUB_TITLE_RIGHT,
	SUB_TITLE_BOTTOM_LEFT,
	SUB_TITLE_BOTTOM,
	SUB_TITLE_BOTTOM_RIGHT,
	SUB_WINDOW_LEFT,
	SUB_WINDOW_BLANK,
	SUB_WINDOW_RIGHT,
	SUB_WINDOW_BOTTOM_LEFT,
	SUB_WINDOW_BOTTOM,
	SUB_WINDOW_BOTTOM_RIGHT,
	BUTTON_TOP_LEFT,
	BUTTON_TOP,
	BUTTON_TOP_RIGHT,
	BUTTON_BOTTOM_LEFT,
	BUTTON_BOTTOM,
	BUTTON_BOTTOM_RIGHT,
	BUTTON_LEFT,
	BUTTON_BLANK,
	BUTTON_RIGHT,
	BUTTONDOWN_TOP_LEFT,
	BUTTONDOWN_TOP,
	BUTTONDOWN_TOP_RIGHT,
	BUTTONDOWN_BOTTOM_LEFT,
	BUTTONDOWN_BOTTOM,
	BUTTONDOWN_BOTTOM_RIGHT,
	BUTTONDOWN_LEFT,
	BUTTONDOWN_BLANK,
	BUTTONDOWN_RIGHT,
	CHECKBOX_UNCHECKED,
	CHECKBOX_PRESSED,
	CHECKBOX_CHECKED,
	RADIO_UNSELECTED,
	RADIO_PRESSED,
	RADIO_SELECTED,
	ICON_LEFT,
	ICON_RIGHT,
	DUMMY,

	// Color 
	BLACK,
	RED_BLACK,
	BLUE,
	GREEN_DARK,
	GREY,
	GREY_DARK,
	GREEN,
	RED_LIGHT,
	GREY_LIGHT, 

	// micro window without title

	MICRO_TOP_LEFT,
	MICRO_TOP,
	MICRO_TOP_RIGHT,
	MICRO_BOTTOM_LEFT,
	MICRO_BOTTOM,
	MICRO_BOTTOM_RIGHT,
	MICRO_LEFT,
	MICRO_BLANK,
	MICRO_RIGHT,


	// micro sub window

	C_01_SUB_MICRO_TOP_LEFT,
	C_02_SUB_MICRO_TOP,
	C_03_SUB_MICRO_TOP_RIGHT,
	C_04_SUB_MICRO_BOTTOM_LEFT,
	C_05_SUB_MICRO_BOTTOM,
	C_06_SUB_MICRO_BOTTOM_RIGHT,
	C_07_SUB_MICRO_LEFT,
	C_08_SUB_MICRO_BLANK,
	C_09_SUB_MICRO_RIGHT,

	// micro sub window
	SUB_S_MICRO_TOP_LEFT,
	SUB_S_MICRO_TOP,
	SUB_S_MICRO_TOP_RIGHT,
	SUB_S_MICRO_BOTTOM_LEFT,
	SUB_S_MICRO_BOTTOM,
	SUB_S_MICRO_BOTTOM_RIGHT,
	SUB_S_MICRO_LEFT,
	SUB_S_MICRO_BLANK,
	SUB_S_MICRO_RIGHT,


	C_10_SUB_MICRO_TOP_RIGHT__SUB_MICRO_TOP_LEFT,
	C_11_SUB_MICRO_TOP_RIGHT__SUB_MICRO_BOTTOM_LEFT__SUB_MICRO_TOP_LEFT,
	C_12_SUB_MICRO_TOP_RIGHT__SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_TOP_LEFT,
	C_13_SUB_MICRO_TOP_RIGHT__SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_BOTTOM_LEFT__SUB_MICRO_TOP_LEFT,
	C_14_SUB_MICRO_TOP_RIGHT__SUB_MICRO_BOTTOM_RIGHT,
	C_15_SUB_MICRO_BOTTOM_LEFT__SUB_MICRO_TOP_LEFT,
	C_16_SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_BOTTOM_LEFT__SUB_MICRO_TOP_LEFT,
	C_17_SUB_MICRO_TOP_RIGHT__SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_BOTTOM_LEFT,
	C_18_SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_BOTTOM_LEFT,
	C_19_SUB_MICRO_TOP_RIGHT__SUB_MICRO_BOTTOM__SUB_MICRO_TOP_LEFT,
	C_20_SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_BOTTOM_LEFT__SUB_MICRO_TOP,
	C_21_SUB_MICRO_TOP_RIGHT__SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_LEFT,
	C_22_SUB_MICRO_BOTTOM_LEFT__SUB_MICRO_TOP_LEFT__SUB_MICRO_RIGHT,
	C_23_SUB_MICRO_TOP__SUB_MICRO_BOTTOM,
	C_24_SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_TOP,
	C_25_SUB_MICRO_BOTTOM_LEFT__SUB_MICRO_TOP,
	C_26_SUB_MICRO_TOP_LEFT__SUB_MICRO_BOTTOM,
	C_27_SUB_MICRO_TOP_RIGHT__SUB_MICRO_BOTTOM,
	C_28_SUB_MICRO_TOP_RIGHT__SUB_MICRO_BOTTOM_LEFT,
	C_29_SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_TOP_LEFT,
	C_30_SUB_MICRO_BOTTOM_RIGHT__SUB_MICRO_LEFT,
	C_31_SUB_MICRO_TOP_LEFT__SUB_MICRO_RIGHT,
	C_32_SUB_MICRO_LEFT__SUB_MICRO_RIGHT,

	DUMMY_01,
	DUMMY_02,
	DUMMY_03,
	DUMMY_04,

	// micro sub window

	C_01_S_SUB_MICRO_TOP_LEFT,
	C_02_S_SUB_MICRO_TOP,
	C_03_S_SUB_MICRO_TOP_RIGHT,
	C_04_S_SUB_MICRO_BOTTOM_LEFT,
	C_05_S_SUB_MICRO_BOTTOM,
	C_06_S_SUB_MICRO_BOTTOM_RIGHT,
	C_07_S_SUB_MICRO_LEFT,
	C_08_S_SUB_MICRO_BLANK,
	C_09_S_SUB_MICRO_RIGHT,
	
	// progress
	
	C_APPLE,
	C_BUG,
	C_DISK,

	BUTTON_RESTORE_BTN,
	BUTTON_UP_BTN,
	BUTTON_DOWN_BTN,
	BUTTON_SAVE_BTN,
	BUTTON_LEFT_BTN,	
	BUTTON_RIGHT_BTN,	

	// progress
	
	C_TCP_WAIT,
	C_TCP_CONNECT,
	C_TCP_RECEIVE,
	C_TCP_TRANSMIT,

	C_TCP_CANCEL,
	BUTTON_ZOOM_BTN,
	
	BUTTON_ADD_LINE,	
	BUTTON_DEL_LINE,
	BUTTON_EDIT_LINE


};

enum TEXT_COLOR {

	TEXT_BLACK1 =15,
	TEXT_GRAY = 14,
	TEXT_GREEN = 13, 
	TEXT_BLUE = 12, 
	TEXT_RED = 11, 
	TEXT_YELLOW = 10, 
	TEXT_WHITE =9,
	TEXT_BRAUN =8,
	TEXT_BRAUN_LIGTH = 7,
	TEXT_BLUE_LIGTH = 6,
	TEXT_BRAUN_LIGTH2 = 5,
	TEXT_DUMMY1 =3,
	TEXT_DUMMY2 =2, 
	TEXT_DUMMY3 =1,
	TEXT_BLACK = 0
};

	
	

